### ISSUE TITLE
Visibility Changed Event not working

### ISSUE THREAD

**Issue by AlinBucea** [vaadin/tree-grid#26]
It seems that hiding/showing columns is not working as it should. (v0.7.5, v0.7.6)

For a specific column I set: column.setHidable(true);
If I'm trying to hide/un-hide it from the UI it will raise an exception and  I won't be able to use treeGrid.addColumnVisibilityChangeListener method to add specific logic. The column is hided but the exception is preventing me using the raised event in other scopes.

The exception is next: 
```
java.lang.IllegalAccessException: Class org.vaadin.treegrid.TreeGrid$1 can not access a member of class com.vaadin.ui.Grid with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at org.vaadin.treegrid.TreeGrid$1.columnVisibilityChanged(TreeGrid.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
	at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119) ......... 
```
I've tried it with versions of Vaadin 7.7.9 and 7.7.10.

**Comment by wbadam** [comment]
Hi, thanks for the report, there was an issue with accessing methods through reflection, fixed now on master.

**Comment by AlinBucea** [comment]
It works now. Thank you for the quick response and fix.
